#
###################################
# Site wide configuration
####################################
#
title: Matt Goodman's Blog
email:
description: A selection of my research and thoughts
url: # the base hostname & protocol for your site
keywords: ["blog", "jekyll"]

#
###################################
# Jekyll configuration
####################################
#
timezone:          America/New_York
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->
permalink:         /articles/:year-:month/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: true

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: Matt Goodman's Blog
  avatar:
  job: It's All Good, Man
  bio: "A selection of my research and thoughts"
  email: mattgoodman13 (.a.t.) gmail (.d.o.t.) com
  disqus-shortname: https-goodmattg-github-io
  twitter: #username
  facebook: #username
  google:
    plus: #username
    analytics:
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: goodmattg
  gitlab: #username
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: matthew-goodman-89b76989
  skype: #username
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  500px: #username
  codepen: #username
  reddit: #username
  telegram: #username
