baseURL = "https://https://goodmattg.github.io/" 
disableKinds = ["taxonomy", "term"] 
enableEmoji = true 
googleAnalytics = "" # add your tracking id
theme = "researcher" 
title = "Matt Goodman" 

[params]
author = "Matthew Goodman" 
description = "A simple monospaced resume theme for Hugo." 
favicon = "favicon.ico" # path to a .ico to use as favicon
logo = "" # url or path to a logo to put in the header
math = true # enable KaTeX (https://katex.org/) globally

[params.footer]
text = "By Matthew Goodman"
url = "https://github.com/ojroques/hugo-researcher"
[params.style] # appearance options (can be omitted)
avatarSize = "120px"
colorBlack = "#222222"
colorRed = "#3f51b5"
fontFamily = "Inconsolata"
pageWidth = "750px"

[permalinks]
"/" = "/:filename"

[menu]
[[menu.main]]
name = "Posts"
url = "/posts"
weight = 1
[[menu.main]]
name = "About"
url = "/about"
weight = 2
# weight = 1
[[menu.main]]
name = "Resume"
url = "/resume.pdf"
weight = 3
# 'pre' and 'post' hooks are available
# here we use an icon from Bootstrap https://icons.getbootstrap.com/
# pre = '<svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-file-earmark-person-fill" fill="currentColor" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M2 2a2 2 0 0 1 2-2h5.293A1 1 0 0 1 10 .293L13.707 4a1 1 0 0 1 .293.707V14a2 2 0 0 1-2 2H4a2 2 0 0 1-2-2V2zm7.5 1.5v-2l3 3h-2a1 1 0 0 1-1-1zM11 8a3 3 0 1 1-6 0 3 3 0 0 1 6 0zm2 5.755S12 12 8 12s-5 1.755-5 1.755V14a1 1 0 0 0 1 1h8a1 1 0 0 0 1-1v-.245z"/></svg> '
[[menu.main]]
name = "Contact"
url = "/contact"
weight = 4
[[menu.main]]
name = "Bookshelf"
url = "/bookshelf"
weight = 2

[markup.goldmark.renderer]
unsafe = true # allow raw HTML in markdown files

[markup.highlight]
linenos = "true"
# style = "solarized-dark"
style = "rrt"
