baseURL = "https://goodmattg.github.io" 
disableKinds = ["taxonomy", "term"] 
enableEmoji = true 
googleAnalytics = "" # add your tracking id
theme = "researcher" 
title = "Matt Goodman" 

[params]
author = "Matthew Goodman" 
description = "The website of Matthew Goodman" 
favicon = "favicon.ico" # path to a .ico to use as favicon
logo = "" # url or path to a logo to put in the header
math = true # enable KaTeX (https://katex.org/) globally

[params.footer]
text = "By Matthew Goodman"

[params.style] # appearance options (can be omitted)
avatarSize = "200px"
colorBlack = "#222222"
colorRed = "#3f51b5"
fontFamily = "Roboto"
pageWidth = "1000px"

[permalinks]
"/" = "/:filename"

[menu]
[[menu.main]]
name = "Posts"
url = "/posts"
weight = 2
[[menu.main]]
name = "About"
url = "/about"
weight = 1
# weight = 1
[[menu.main]]
name = "Resume"
url = "/resume"
weight = 3
[[menu.main]]
name = "Contact"
url = "/contact"
weight = 4
[[menu.main]]
name = "Bookshelf"
url = "/bookshelf"
weight = 3
[[menu.main]]
name = "Quotes"
url = "/quotes"
weight = 3

[markup.goldmark.renderer]
unsafe = true # allow raw HTML in markdown files

[markup.highlight]
linenos = "true"
style = "monokai"
