baseURL = "https://goodmattg.github.io" 
disableKinds = ["taxonomy", "term"] 
enableEmoji = true 
env = "production" 
googleAnalytics = "" # add your tracking id
theme = "PaperMod" 
title = "Matt's Log" 

[params]
ShowCodeCopyButtons = true
author = "Matthew Goodman"
description = "The website of Matthew Goodman"

logo = "" # url or path to a logo to put in the header
math = true # enable KaTeX (https://katex.org/) globally

[params.homeInfoParams]
Content = "Welcome to Matt's Log"
Title = "Hi there wave"

# [[socialIcons]]
# name = "twitter"
# url = "https://twitter.com/"
# [[socialIcons]]
# name = "stackoverflow"
# url = "https://stackoverflow.com"
# [[socialIcons]]
# name = "github"
# url = "https://github.com/"

[params.assets]
favicon = "magnet.ico" # path to a .ico to use as favicon

[params.footer]
text = "By Matthew Goodman"

[params.style] # appearance options (can be omitted)
avatarSize = "200px"
colorBlack = "#222222"
colorRed = "#3f51b5"
fontFamily = "Georgia"
pageWidth = "1000px"

[permalinks]
"/" = "/:filename"

[menu]
[[menu.main]]
name = "Posts"
url = "/posts"
weight = 1
[[menu.main]]
name = "About"
url = "/about"
weight = 2
[[menu.main]]
name = "Bookshelf"
url = "/bookshelf"
weight = 3
[[menu.main]]
name = "Quotes"
url = "/quotes"
weight = 3
[[menu.main]]
name = "Contact"
url = "/contact"
weight = 4

[markup.goldmark.renderer]
unsafe = true # allow raw HTML in markdown files

[markup.highlight]
linenos = "true"
style = "solarized-dark256"
