description = "A simple monospaced resume theme for Hugo."
features = ["bootstrap", "responsive", "simple"]
homepage = "https://github.com/ojroques/hugo-researcher"
license = "GPL-3.0"
licenselink = "https://github.com/ojroques/hugo-researcher/blob/master/LICENSE"
min_version = "0.74.3"
name = "Researcher - Matt Custom"
tags = ["blog", "bootstrap", "clean", "minimal", "personal", "responsive", "resume", "simple"]

[author]
homepage = "https://goodmattg.github.io"
name = "Matthew Goodman"

[original]
author = "Ankit Sultana"
homepage = "https://github.com/ankitsultana"
repo = "https://github.com/ankitsultana/researcher"
